name: dart_carte_du_jour
version: 0.0.0-pre.0
authors:
- Adam Singer <financeCoding@gmail.com>
description: Service that generates package documentation for pub.dartlang.org
homepage: https://github.com/financeCoding/dart-carte-du-jour
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: ">=0.10.0+2 <0.11.0"
  google_datastore_v1beta1_api: ">=0.4.6 <0.5.0"
  http: ">=0.9.0 <0.11.0"
  meta: ">=0.8.8 <0.9.0"
  path: ">=1.1.0 <2.0.0"
  logging: ">=0.9.0 <0.10.0"
  crypto: any
dev_dependencies:
  unittest: ">=0.10.1+2 <0.11.0"
